"""
Mailgi logo generator.  python3 genlogo.py  ->  logo.svg, logo.png, logo-<n>.png

The mark is the wordmark's lowercase italic slab-serif 'm', built from GEOMETRY,
not text. favicon.svg sets a live <text> in "Newsreader, Georgia, serif": fine
for a browser tab, wrong for a logo, because anyone rasterising it without
Newsreader installed silently gets a different letterform.

Two bugs worth not reintroducing:
  * Pillow's stroked arc() leaves a seam at its midpoint -> dark notches inside
    the counters. Hence filled shapes with punched counters, never strokes.
  * Shapes that ABUT along an edge leave an antialiasing hairline; it showed as
    a 1px line across the letter at the spring line. Every join here OVERLAPS
    by OVERLAP px, and the counters are one continuous path rather than a
    half-disc stacked on a rectangle.

One geometry description drives both the raster and the vector, so they cannot
drift apart. Palette is the site's own (styles.css).
"""
from PIL import Image, ImageDraw

INK, PAPER, CLEAR = (0x16,0x21,0x1f,255), (0xfb,0xfb,0xfa,255), (0,0,0,0)
S, SS = 512, 4
N = S * SS

STEM_X = (176, 256, 336)
Y_TOP, Y_BASE = 208, 344
R, W, SLANT = 40, 34, 0.16
SERIF_W, SERIF_H = 27, 11
RADIUS = 112
OVERLAP = 8              # how far joins interpenetrate
HW = W / 2.0
ARCH_CX = (STEM_X[0] + R, STEM_X[1] + R)

# ── geometry, described once ───────────────────────────────────────────────
def shapes():
    add, sub = [], []
    for cx in ARCH_CX:                                   # shoulders
        add.append(("halfdisc", cx, Y_TOP, R + HW))
    for x in STEM_X:                                     # stems, up into shoulders
        add.append(("rect", x - HW, Y_TOP - OVERLAP, x + HW, Y_BASE))
    for cx in ARCH_CX:                                   # counters, one path each
        sub.append(("stadium", cx, Y_TOP, R - HW, Y_BASE + SERIF_H))
    feet = [("rect", x - SERIF_W, Y_BASE - SERIF_H, x + SERIF_W, Y_BASE + SERIF_H)
            for x in STEM_X]
    return add, sub, feet

# ── raster ─────────────────────────────────────────────────────────────────
def paint(d, sh, fill, k):
    kind = sh[0]
    if kind == "rect":
        _, x0, y0, x1, y1 = sh
        d.rectangle([x0*k, y0*k, x1*k, y1*k], fill=fill)
    elif kind == "halfdisc":
        _, cx, cy, r = sh
        d.pieslice([(cx-r)*k, (cy-r)*k, (cx+r)*k, (cy+r)*k], 180, 360, fill=fill)
    elif kind == "stadium":
        _, cx, cy, r, y1 = sh
        d.pieslice([(cx-r)*k, (cy-r)*k, (cx+r)*k, (cy+r)*k], 180, 360, fill=fill)
        d.rectangle([(cx-r)*k, (cy-OVERLAP)*k, (cx+r)*k, y1*k], fill=fill)

def svg_path(sh):
    kind = sh[0]
    if kind == "rect":
        _, x0, y0, x1, y1 = sh
        return f'<rect x="{x0}" y="{y0}" width="{x1-x0}" height="{y1-y0}"/>'
    if kind == "halfdisc":
        _, cx, cy, r = sh
        return f'<path d="M{cx-r},{cy} A{r},{r} 0 0 1 {cx+r},{cy} Z"/>'
    _, cx, cy, r, y1 = sh                      # stadium: one continuous outline
    return (f'<path d="M{cx-r},{y1} L{cx-r},{cy} A{r},{r} 0 0 1 {cx+r},{cy} '
            f'L{cx+r},{y1} Z"/>')

add, sub, feet = shapes()
mark = Image.new("RGBA", (N, N), CLEAR)
d = ImageDraw.Draw(mark)
for s in add:  paint(d, s, PAPER, SS)
for s in sub:  paint(d, s, CLEAR, SS)
for s in feet: paint(d, s, PAPER, SS)

dy = Y_BASE * SS
mark = mark.transform((N, N), Image.AFFINE, (1, SLANT, -SLANT*dy, 0, 1, 0),
                      resample=Image.BICUBIC).resize((S, S), Image.LANCZOS)

TARGET = 312.0
b = mark.getbbox()
scale = TARGET / max(b[2]-b[0], b[3]-b[1])
tx, ty = (b[0]+b[2])/2.0, (b[1]+b[3])/2.0
mark = mark.transform((S, S), Image.AFFINE,
                      (1/scale, 0, tx - S/(2*scale), 0, 1/scale, ty - S/(2*scale)),
                      resample=Image.BICUBIC)

ground = Image.new("RGBA", (N, N), CLEAR)
ImageDraw.Draw(ground).rounded_rectangle([0, 0, N-1, N-1], radius=RADIUS*SS, fill=INK)
logo = Image.alpha_composite(ground.resize((S, S), Image.LANCZOS), mark)
logo.save("logo.png")
for n in (24, 32, 48, 64, 128, 180, 192, 256):   # 180 = apple-touch-icon
    logo.resize((n, n), Image.LANCZOS).save(f"logo-{n}.png")

# opaque variant: same art, corners filled rather than cut away
opaque = Image.new("RGBA", (S, S), INK)
opaque.alpha_composite(logo)
opaque.convert("RGB").save("logo-square.png")

# ── vector, from the same shapes ───────────────────────────────────────────
xform = (f"translate({S/2},{S/2}) scale({scale:.5f}) translate({-tx:.3f},{-ty:.3f}) "
         f"matrix(1 0 {-SLANT} 1 {SLANT*Y_BASE:.3f} 0)")
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {S} {S}" width="{S}" height="{S}" role="img" aria-label="Mailgi">
  <title>Mailgi</title>
  <!-- Generated by genlogo.py from the same geometry as logo.png. Joins overlap
       by {OVERLAP}px: abutting edges leave an antialiasing hairline. -->
  <rect width="{S}" height="{S}" rx="{RADIUS}" fill="#16211f"/>
  <mask id="mailgi-m" maskUnits="userSpaceOnUse" x="0" y="0" width="{S}" height="{S}">
    <g transform="{xform}">
      <g fill="#fff">{''.join(svg_path(s) for s in add)}</g>
      <g fill="#000">{''.join(svg_path(s) for s in sub)}</g>
      <g fill="#fff">{''.join(svg_path(s) for s in feet)}</g>
    </g>
  </mask>
  <rect width="{S}" height="{S}" fill="#fbfbfa" mask="url(#mailgi-m)"/>
</svg>
'''
open("logo.svg", "w").write(svg)
print("regenerated; scale %.4f bbox %s" % (scale, b))
